// Generated by SymbolCraft
import SwiftUI

/// Custom SF Symbols generated by SymbolCraft.
public enum GeneratedSymbol: String, CaseIterable {
    case abTestingMdi = "AbTestingMdi"
    case abacusMdi = "AbacusMdi"
    case airplayOutlined = "AirplayOutlined"
    case arrowBackFill = "ArrowBackFill"
    case arrowBackOfficial = "ArrowBackOfficial"
    case githubSimpleIcons = "GithubSimpleIcons"
    case homeFill = "HomeFill"
    case homeOfficial = "HomeOfficial"
    case homeOutlined = "HomeOutlined"
    case homeOutlinedFill = "HomeOutlinedFill"
    case homeRounded = "HomeRounded"
    case personFill = "PersonFill"
    case personOfficial = "PersonOfficial"
    case personOutlined = "PersonOutlined"
    case personRounded = "PersonRounded"
    case personSharp = "PersonSharp"
    case searchFill = "SearchFill"
    case searchOfficial = "SearchOfficial"
    case searchOutlined = "SearchOutlined"
    case settingsFill = "SettingsFill"
    case settingsOfficial = "SettingsOfficial"
    case settingsOutlined = "SettingsOutlined"
    case settingsRoundedFill = "SettingsRoundedFill"
    case telephoneSvgrepoCom = "TelephoneSvgrepoCom"
    case testSvgsPenSvgrepoCom = "TestSvgsPenSvgrepoCom"

    /// The symbol as a SwiftUI `Image`.
    public var image: Image { Image(rawValue) }
}

public extension Image {
    /// Creates an image from a SymbolCraft-generated symbol.
    init(symbol: GeneratedSymbol) {
        self.init(symbol.rawValue)
    }
}

public extension GeneratedSymbol {
    /// Multiplier converting an artwork box size (points) to the font point
    /// size that renders the symbol at exactly that visual size.
    /// Derived from the template geometry: 1 / (1.7 × 0.7 × 1.0).
    static var pointScale: CGFloat { 0.8403361344537815 }

    /// The symbol rendered so its artwork fills a square of `boxSize` points,
    /// independent of the surrounding font size.
    func image(boxSize: CGFloat) -> some View {
        Image(symbol: self)
            .font(.system(size: boxSize * GeneratedSymbol.pointScale))
    }
}
