// Generated by SymbolCraft
import SwiftUI

/// Custom SF Symbols generated by SymbolCraft.
public enum GeneratedSymbol: String, CaseIterable {
    case abTestingMdi = "AbTestingMdi"
    case abacusMdi = "AbacusMdi"
    case arrowBackFill = "ArrowBackFill"
    case arrowBackOfficial = "ArrowBackOfficial"
    case githubSimpleIcons = "GithubSimpleIcons"
    case homeFill = "HomeFill"
    case homeOfficial = "HomeOfficial"
    case homeOutlined = "HomeOutlined"
    case homeOutlinedFill = "HomeOutlinedFill"
    case homeRounded = "HomeRounded"
    case personFill = "PersonFill"
    case personOfficial = "PersonOfficial"
    case personOutlined = "PersonOutlined"
    case personRounded = "PersonRounded"
    case personSharp = "PersonSharp"
    case searchFill = "SearchFill"
    case searchOfficial = "SearchOfficial"
    case searchOutlined = "SearchOutlined"
    case settingsFill = "SettingsFill"
    case settingsOfficial = "SettingsOfficial"
    case settingsOutlined = "SettingsOutlined"
    case settingsRoundedFill = "SettingsRoundedFill"
    case telephoneSvgrepoCom = "TelephoneSvgrepoCom"

    /// The symbol as a SwiftUI `Image`.
    public var image: Image { Image(rawValue) }
}

public extension Image {
    /// Creates an image from a SymbolCraft-generated symbol.
    init(symbol: GeneratedSymbol) {
        self.init(symbol.rawValue)
    }
}
