package io.github.archivesteak.symbolcraft.plugin

import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.provider.Property

/**
 * DSL exposed as `symbolCraftCompose { }` by [SymbolCraftComposePlugin].
 *
 * @property sourceSet Kotlin source set receiving the generated Compose sources. Unset means
 *   `commonMain` for multiplatform projects and `main` otherwise.
 */
abstract class SymbolCraftComposeExtension {
    abstract val sourceSet: Property<String>
}

/**
 * Consumer plugin registered as `io.github.archivesteak.symbolcraft.compose`.
 *
 * Apply it to a Kotlin project that should compile the Compose sources generated by another
 * project, then declare the producer:
 * ```kotlin
 * plugins { id("io.github.archivesteak.symbolcraft.compose") }
 * dependencies { symbolCraft(project(":shared")) }
 * ```
 *
 * The generated directory is added to the configured source set and the producer task runs before
 * Kotlin compilation, without this project referencing the producer's tasks.
 */
class SymbolCraftComposePlugin : Plugin<Project> {
    override fun apply(project: Project) {
        val extension =
            project.extensions.create("symbolCraftCompose", SymbolCraftComposeExtension::class.java)
        val sources =
            SymbolCraftVariants.resolvable(
                project,
                SymbolCraftVariants.COMPOSE_RESOLVABLE,
                SymbolCraftVariants.COMPOSE_SOURCES,
            )
        ComposeSourceWiring.wire(project, extension.sourceSet, sources, warnIfNoKotlin = true)
    }
}
