import io.github.archivesteak.symbolcraft.model.*
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidLibrary)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.symbolCraft)
}

kotlin {
    androidTarget {
        compilerOptions {
            jvmTarget.set(JvmTarget.JVM_17)
        }
    }

    jvm()

    listOf(
        iosArm64(),
        iosSimulatorArm64()
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    applyDefaultHierarchyTemplate()

    sourceSets {
        // Generated Compose ImageVectors live in this intermediate source set, shared by the
        // Android and Desktop compilations only. The iOS framework never sees Compose.
        val composeMain by creating {
            dependsOn(commonMain.get())
            dependencies {
                implementation(libs.compose.runtime)
                implementation(libs.compose.ui)
                implementation(libs.compose.foundation) // generated @Preview functions use Box/Image
                implementation(libs.compose.ui.tooling.preview)
            }
        }
        androidMain.get().dependsOn(composeMain)
        jvmMain.get().dependsOn(composeMain)
    }
}

android {
    namespace = "io.github.archivesteak.example.shared"
    compileSdk = libs.versions.android.compileSdk.get().toInt()
    defaultConfig {
        minSdk = libs.versions.android.minSdk.get().toInt()
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
}

symbolCraft {
    packageName.set("io.github.archivesteak.example")

    // Compose sources go to build/generated/symbolcraft/compose and join `composeMain`, so the
    // Android app and the Desktop app get them through their dependency on :shared.
    composeSourceSet.set("composeMain")
    generatePreview.set(true)

    // SwiftUI output: build/generated/symbolcraft/swiftui/SymbolCraft.xcassets + Symbols.swift.
    // Regenerated by the same Gradle run Xcode makes to embed the Shared framework; the iOS
    // project references both files (see iosApp/iosApp.xcodeproj).
    swiftUI {
        enabled.set(true)
    }

    naming {
        pascalCase()
    }

    // Material Symbols examples
    materialSymbol("search") {
        standardWeights() // Adds 400, 500, 700 weights with outlined variant
    }

    materialSymbol("home") {
        weights(400, 500, variant = SymbolVariant.ROUNDED) // Specify variant
        bothFills(weight = 400) // Both filled and unfilled
    }

    materialSymbol("person") {
        allVariants(weight = SymbolWeight.W500) // All variants (outlined, rounded, sharp)
    }

    materialSymbol("settings") {
        style(weight = 400, variant = SymbolVariant.OUTLINED)
        style(weight = 500, variant = SymbolVariant.ROUNDED, fill = SymbolFill.FILLED)
    }

    // Apple-only icon: emitted as a .symbolset for SwiftUI, but NOT as Compose sources
    // (no point shipping an AirPlay ImageVector to Android/Desktop).
    materialSymbol("airplay") {
        style(weight = 400, variant = SymbolVariant.OUTLINED)
        swiftUIOnly()
    }

    // External icons with URL template
    externalIcons("abacus", "ab-testing", libraryName = "mdi") {
        urlTemplate = "https://cdn.jsdelivr.net/npm/@mdi/svg@latest/svg/{name}.svg"
    }

    // External icons with multiple style variants using the styleParam API
    externalIcons("home", "search", "person", "settings", "arrow_back", libraryName = "official") {
        urlTemplate = "https://cdn.jsdelivr.net/npm/@material-symbols/svg-400@latest/rounded/{name}{fill}.svg"
        styleParam("fill") {
            values("", "-fill")  // unfilled, filled variants
        }
    }

    // Local icons checked into this module
    localIcons("local-test") {
        directory = "icons"
        include("**/*.svg")
    }

    // Simple Icons - for testing Locale issue (GitHub issue #38)
    externalIcons("github", libraryName = "simple-icons") {
        urlTemplate = "https://simpleicons.org/icons/{name}.svg"
    }
}
