package io.github.archivesteak.symbolcraft.tasks.internal

import io.github.archivesteak.symbolcraft.SymbolCraftDefaults
import io.github.archivesteak.symbolcraft.model.IconConfig
import java.io.File
import org.gradle.api.logging.Logger

/**
 * Deletes files SymbolCraft produced in earlier runs so dropped icons never leave orphans behind.
 *
 * Every deletion of a source file is guarded by [SymbolCraftDefaults.GENERATED_FILE_HEADER]: a
 * hand-written file that happens to live in a generated-output directory is reported and kept.
 */
internal class GeneratedFileCleaner(private val logger: Logger) {

    /**
     * Removes generated Kotlin sources below `<outputDir>/<package>/icons` plus the `__Icons.kt`
     * accessor, then prunes directories left empty.
     *
     * @return number of deleted files
     */
    fun cleanGeneratedKotlin(outputDir: File, packageName: String): Int {
        val packagePath = packageName.replace('.', '/')
        val iconsBaseDir = File(outputDir, "$packagePath/icons")
        val mainSymbolsFile = File(outputDir, "$packagePath/__Icons.kt")

        var cleanedCount = 0

        if (iconsBaseDir.exists()) {
            iconsBaseDir.walkTopDown().forEach { file ->
                if (file.isFile && file.extension == "kt") {
                    logger.debug(
                        "Cleaning old generated file: ${file.relativeTo(iconsBaseDir).path}"
                    )
                    if (deleteGeneratedSource(file)) cleanedCount++
                }
            }
            iconsBaseDir
                .walkBottomUp()
                .filter { it.isDirectory && it.listFiles()?.isEmpty() == true }
                .forEach { it.delete() }
        }

        if (mainSymbolsFile.exists()) {
            logger.debug("Cleaning main symbols file")
            if (deleteGeneratedSource(mainSymbolsFile)) cleanedCount++
        }

        if (cleanedCount > 0) {
            logger.lifecycle("Cleaned $cleanedCount old generated Kotlin files")
        }
        return cleanedCount
    }

    /**
     * Removes every `.symbolset` bundle directly inside [catalogDir] and a generated
     * `Symbols.swift` stored next to them.
     *
     * @return number of deleted entries
     */
    fun cleanSymbolSets(catalogDir: File): Int {
        if (!catalogDir.exists()) return 0

        var cleanedCount = 0
        catalogDir.listFiles()?.forEach { file ->
            when {
                file.isDirectory && file.name.endsWith(".symbolset") -> {
                    logger.debug("Cleaning old symbol set: ${file.name}")
                    file.deleteRecursively()
                    cleanedCount++
                }
                file.isFile && file.name == SymbolCraftDefaults.SWIFT_SOURCE_NAME -> {
                    if (deleteGeneratedSource(file)) cleanedCount++
                }
            }
        }

        if (cleanedCount > 0) {
            logger.lifecycle("Cleaned $cleanedCount old SwiftUI generated files")
        }
        return cleanedCount
    }

    /**
     * Deletes a generated source file (Kotlin or Swift) only when it carries the SymbolCraft
     * header, so a user's own file with the same name is never touched.
     *
     * @return true when the file was actually deleted
     */
    fun deleteGeneratedSource(file: File): Boolean {
        if (!file.isFile) return false
        if (!file.readText().startsWith(SymbolCraftDefaults.GENERATED_FILE_HEADER)) {
            logger.warn("   Refusing to delete ${file.absolutePath}: not generated by SymbolCraft")
            return false
        }
        if (!file.delete()) {
            logger.warn("   Failed to delete: ${file.absolutePath}")
            return false
        }
        return true
    }

    /**
     * Deletes SVG cache files that no longer map to any requested icon signature.
     *
     * Cache files are named after `IconConfig#getCacheKey`, so once a configuration entry
     * disappears the orphaned payload can be identified deterministically.
     */
    fun cleanUnusedCache(cacheDir: File, config: Map<String, List<IconConfig>>): Int {
        if (!cacheDir.exists()) return 0

        val requiredCacheKeys =
            config
                .flatMap { (iconName, iconConfigs) ->
                    iconConfigs.map { iconConfig -> iconConfig.getCacheKey(iconName) }
                }
                .toSet()

        var cleanedCount = 0
        cacheDir.listFiles()?.forEach { file ->
            if (file.isFile && file.nameWithoutExtension !in requiredCacheKeys) {
                logger.debug("Cleaning unused cache file: ${file.name}")
                if (file.delete()) {
                    cleanedCount++
                } else {
                    logger.warn("   Failed to delete unused cache file: ${file.absolutePath}")
                }
            }
        }

        if (cleanedCount > 0) {
            logger.lifecycle("Cleaned $cleanedCount unused cache files")
        }
        return cleanedCount
    }
}
