package io.github.archivesteak.symbolcraft.tasks.internal

import io.github.archivesteak.symbolcraft.model.IconConfig
import io.github.archivesteak.symbolcraft.utils.PathUtils
import java.io.File
import org.gradle.api.logging.Logger

/**
 * Performs filesystem hygiene before generation begins.
 *
 * Responsibilities include:
 * * removing previously generated Kotlin files so the next pass produces deterministic output
 * * pruning stale cache entries when we know the cache is isolated to the current project
 * * emitting detailed logs so contributors understand *why* files disappear
 */
internal class PreGenerationCleaner(private val logger: Logger) {

    fun clean(context: GenerationContext) {
        cleanOldGeneratedFiles(context.outputDir, context.packageName)
        context.swiftUIOutputDir?.let { cleanOldSymbolSets(it) }
        context.swiftUISourceDir?.let { sourceDir ->
            if (sourceDir != context.swiftUIOutputDir) {
                // The Swift source may live in a shared user folder (asset-catalog parent or a
                // custom swiftSourceOutputDirectory): only delete if it is provably ours.
                deleteGeneratedSwiftSource(File(sourceDir, "Symbols.swift"))
            }
        }

        val cacheEnabled = context.extension.cacheEnabled.get()
        if (cacheEnabled && shouldCleanCache(context.cacheBaseDir, context.projectBuildDir)) {
            cleanUnusedCache(context.svgCacheDir, context.config)
        }
    }

    /**
     * Deletes `Symbols.swift` only when it carries the SymbolCraft header, so a user's own file
     * with the same name is never touched.
     *
     * @return true when the file was actually deleted
     */
    private fun deleteGeneratedSwiftSource(file: File): Boolean {
        if (!file.isFile) return false
        if (!file.readText().startsWith("// Generated by SymbolCraft")) {
            logger.warn("   Refusing to delete ${file.absolutePath}: not generated by SymbolCraft")
            return false
        }
        logger.debug("Cleaning old ${file.name}")
        return file.delete()
    }

    /**
     * Removes `.symbolset` bundles and the `Symbols.swift` helper emitted by previous runs so
     * dropped icons do not leave orphaned symbol sets behind.
     */
    private fun cleanOldSymbolSets(swiftUIOutputDir: File) {
        if (!swiftUIOutputDir.exists()) return

        var cleanedCount = 0

        swiftUIOutputDir.listFiles()?.forEach { file ->
            when {
                file.isDirectory && file.name.endsWith(".symbolset") -> {
                    logger.debug("Cleaning old symbol set: ${file.name}")
                    file.deleteRecursively()
                    cleanedCount++
                }
                file.isFile && file.name == "Symbols.swift" -> {
                    if (deleteGeneratedSwiftSource(file)) cleanedCount++
                }
            }
        }

        if (cleanedCount > 0) {
            logger.lifecycle("Cleaned $cleanedCount old SwiftUI generated files")
        }
    }

    /**
     * Determines whether it is safe to delete cache entries.
     *
     * Shared caches (outside the consumer build directory) are intentionally preserved because
     * multiple projects or IDE syncs may reuse them concurrently; nuking shared directories would
     * introduce subtle race conditions.
     */
    private fun shouldCleanCache(cacheBaseDir: File, projectBuildDir: String): Boolean {
        val isInsideBuildDir = PathUtils.isCacheInsideBuildDir(cacheBaseDir, File(projectBuildDir))

        if (!isInsideBuildDir) {
            logger.lifecycle("Cache cleanup skipped: Using shared cache outside build directory")
            logger.lifecycle("   Cache location: ${cacheBaseDir.canonicalFile.absolutePath}")
            logger.lifecycle("   Shared caches are preserved to avoid conflicts across projects")
        }

        return isInsideBuildDir
    }

    /**
     * Removes Kotlin files emitted by previous runs so we never end up with orphaned classes after
     * configuration changes (for instance when a user drops an icon from their DSL block).
     */
    private fun cleanOldGeneratedFiles(outputDir: File, packageName: String) {
        val packagePath = packageName.replace('.', '/')
        val iconsBaseDir = File(outputDir, "$packagePath/icons")
        val mainSymbolsFile = File(outputDir, "$packagePath/__Icons.kt")

        var cleanedCount = 0

        if (iconsBaseDir.exists()) {
            iconsBaseDir.walkTopDown().forEach { file ->
                if (file.isFile && file.extension == "kt") {
                    logger.debug(
                        "Cleaning old generated file: ${file.relativeTo(iconsBaseDir).path}"
                    )
                    file.delete()
                    cleanedCount++
                }
            }
        }

        if (mainSymbolsFile.exists()) {
            logger.debug("Cleaning main symbols file")
            mainSymbolsFile.delete()
            cleanedCount++
        }

        if (cleanedCount > 0) {
            logger.lifecycle("Cleaned $cleanedCount old generated files")
        }
    }

    /**
     * Deletes SVG cache files that no longer map to any requested icon signature.
     *
     * Cache files are named after `IconConfig#getCacheKey`, so once a configuration entry
     * disappears, we can deterministically identify the orphaned payload and drop it.
     */
    private fun cleanUnusedCache(cacheDir: File, config: Map<String, List<IconConfig>>) {
        if (!cacheDir.exists()) return

        val requiredCacheKeys =
            config
                .flatMap { (iconName, iconConfigs) ->
                    iconConfigs.map { iconConfig -> iconConfig.getCacheKey(iconName) }
                }
                .toSet()

        var cleanedCount = 0

        cacheDir.listFiles()?.forEach { file ->
            if (file.isFile) {
                val cacheKey = file.nameWithoutExtension
                if (cacheKey !in requiredCacheKeys) {
                    logger.debug("Cleaning unused cache file: ${file.name}")
                    if (file.delete()) {
                        cleanedCount++
                    } else {
                        logger.warn("   Failed to delete unused cache file: ${file.absolutePath}")
                    }
                }
            }
        }

        if (cleanedCount > 0) {
            logger.lifecycle("Cleaned $cleanedCount unused cache files")
        }
    }
}
