package io.github.archivesteak.symbolcraft

/** Default values shared by the SymbolCraft DSL and generation pipeline. */
object SymbolCraftDefaults {
    const val PREVIEW_ANNOTATION_CLASS = "androidx.compose.ui.tooling.preview.Preview"

    /**
     * First line of every file SymbolCraft generates (Kotlin sources, `Symbols.swift`). Cleanup
     * code refuses to delete files without this marker, so hand-written files that happen to live
     * in a generated-output directory are never destroyed.
     */
    const val GENERATED_FILE_HEADER = "// Generated by SymbolCraft"

    /** Task group shown by `gradle tasks`. */
    const val TASK_GROUP = "symbolcraft"

    /** Downloaded SVG workspace, relative to the build directory. */
    const val SVG_OUTPUT_DIR = "symbolcraft/svgs"

    /** Default Compose source output, relative to the build directory. */
    const val COMPOSE_OUTPUT_DIR = "generated/symbolcraft/compose"

    /** Default SwiftUI output root, relative to the build directory. */
    const val SWIFTUI_OUTPUT_DIR = "generated/symbolcraft/swiftui"

    /** Name of the generated Xcode asset catalog. */
    const val SWIFTUI_CATALOG_NAME = "SymbolCraft.xcassets"

    /** Name of the generated Swift helper source. */
    const val SWIFT_SOURCE_NAME = "Symbols.swift"
}
