package io.github.archivesteak.symbolcraft

/** Default values shared by the SymbolCraft DSL and generation pipeline. */
object SymbolCraftDefaults {
    const val PREVIEW_ANNOTATION_CLASS = "androidx.compose.ui.tooling.preview.Preview"

    /**
     * First line of every file SymbolCraft generates (Kotlin sources, `Symbols.swift`). Cleanup
     * code refuses to delete files without this marker, so hand-written files that happen to live
     * in a generated-output directory are never destroyed.
     */
    const val GENERATED_FILE_HEADER = "// Generated by SymbolCraft"
}
